#!/usr/bin/env python3
"""
reading-to-viz.py
Pure CLI starter for "reading → extract concepts → archviz learning artifacts" workflow.
Adaptation of qiaomu-english-learn pattern (consume content, extract vocab/concepts, turn into reviewable + spaced-rep artifacts) but using archviz for visual outputs (mindmaps, cards, ASCII, diagrams) instead of/in addition to text flashcards.

Usage (absolute paths):
  python3 /Users/mac/Developer/archviz-skills/scripts/reading-to-viz.py \
      --input /tmp/reading-session.md \
      --output-dir /Users/mac/Developer/archviz-skills/outputs/reading-$(date +%Y-%m-%d)

Requirements: Python 3, pyyaml (optional for structured), archviz templates or direct Mermaid/ASCII generation.
For full agent use: feed to Claude Code / Grok with prompt referencing this script + archviz.

Outputs (restrained, text-first + optional polished):
- concepts.json (extracted)
- concept-mindmap.mmd (Mermaid)
- concept-mindmap-ascii.txt (plain 80-col fallback)
- vocab-cards.html (self-contained editorial cards for review)
- review-log.md (for spaced-rep tracking / Ebbinghaus notes)

Integrate with:
- qiaomu-markdown-proxy or similar for capture
- Anki/Obsidian export (add simple converter)
- archviz CLI or agent prompt for generation
"""

import argparse
import json
import re
import subprocess
from datetime import datetime
from pathlib import Path
import sys

ARCHVIZ_ROOT = Path("/Users/mac/Developer/archviz-skills")
OUTPUT_BASE = ARCHVIZ_ROOT / "outputs"

def extract_concepts(text: str) -> list[dict]:
    """
    Simple extraction stub. In real workflow, replace with:
    - Agent prompt (Claude Code / Grok): "Extract 5-12 key concepts/vocab from this text. For each: term, short def (1 sentence), relations (list), example if English learning."
    - Or integrate NotebookLM-style processing.
    - Or use qiaomu-style content tools.
    Output format for archviz: list of {"term": , "def": , "relations": [], "example": ""}
    """
    # Placeholder: naive split on sentences or bullets. Real: call LLM or use structured parser.
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    concepts = []
    for i, line in enumerate(lines[:12]):  # limit for focus
        if len(line) > 20:  # rough filter
            term = re.sub(r'[^a-zA-Z0-9\s\-]', '', line.split()[0])[:40]
            concepts.append({
                "term": term or f"Concept-{i}",
                "def": line[:120] + ("..." if len(line) > 120 else ""),
                "relations": [],
                "example": ""
            })
    if not concepts:
        concepts = [{"term": "SampleTerm", "def": "Extracted from reading session.", "relations": ["related-concept"], "example": "Use in sentence."}]
    return concepts

def generate_mindmap(concepts: list[dict]) -> str:
    """Generate simple Mermaid mindmap using archviz-friendly structure."""
    lines = ["mindmap", "  root((Key Concepts from Reading))"]
    for c in concepts:
        lines.append(f"    {c['term']}")
        if c.get("def"):
            lines.append(f"      def[{c['def'][:60]}]")
        for rel in c.get("relations", [])[:3]:
            lines.append(f"      --> {rel}")
    return "\n".join(lines)

def generate_ascii_cards(concepts: list[dict]) -> str:
    """Plain 80-col ASCII fallback cards (no box-drawing, per archviz rules)."""
    cards = []
    for c in concepts:
        card = [
            f"[ {c['term']} ]",
            f"  {c['def']}",
        ]
        if c.get("example"):
            card.append(f"  ex: {c['example'][:50]}")
        cards.append("\n".join(card))
        cards.append("")  # separator
    return "\n".join(cards)[:2000]  # cap size

def generate_html_cards(concepts: list[dict], title: str) -> str:
    """Self-contained restrained HTML cards (Warm Paper / Editorial style, copy from archviz templates/html/editorial-card.html logic)."""
    # Minimal inline version for standalone. In real: use archviz html template + tokens.
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>
body {{ font-family: system-ui, sans-serif; background:#f5f0eb; color:#1B365D; max-width:720px; margin:2rem auto; padding:1rem; }}
.card {{ background:white; border:1px solid #a8a29e; padding:1rem; margin-bottom:1rem; border-radius:0; }}
.term {{ font-weight:600; font-size:1.1rem; }}
.def {{ margin:0.5rem 0; }}
.rel {{ font-size:0.9rem; color:#666; }}
</style></head><body>
<h1>{title}</h1>
<p>Generated by archviz reading-to-viz workflow. Review daily, space repetitions.</p>
"""
    for c in concepts:
        html += f"""<div class="card">
<div class="term">{c['term']}</div>
<div class="def">{c['def']}</div>
{"<div class='rel'>Relations: " + ", ".join(c.get('relations',[])) + "</div>" if c.get('relations') else ""}
</div>"""
    html += "</body></html>"
    return html

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to captured reading text (md/txt)")
    parser.add_argument("--output-dir", default=None, help="Absolute output dir (default: archviz/outputs/reading-YYYY-MM-DD)")
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    if not input_path.exists():
        print(f"ERROR: input not found: {input_path}")
        sys.exit(1)

    text = input_path.read_text(encoding="utf-8", errors="ignore")
    concepts = extract_concepts(text)

    date_str = datetime.now().strftime("%Y-%m-%d")
    out_dir = Path(args.output_dir) if args.output_dir else (OUTPUT_BASE / f"reading-{date_str}")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write artifacts
    (out_dir / "concepts.json").write_text(json.dumps(concepts, ensure_ascii=False, indent=2), encoding="utf-8")

    mindmap = generate_mindmap(concepts)
    (out_dir / "concept-mindmap.mmd").write_text(mindmap, encoding="utf-8")

    ascii_cards = generate_ascii_cards(concepts)
    (out_dir / "concept-cards-ascii.txt").write_text(ascii_cards, encoding="utf-8")

    html_cards = generate_html_cards(concepts, f"Reading Viz — {date_str}")
    (out_dir / "vocab-cards.html").write_text(html_cards, encoding="utf-8")

    # Simple review log stub (for Ebbinghaus / spaced rep tracking)
    log = f"""# Review Log for {date_str}
Source: {input_path}
Concepts extracted: {len(concepts)}

## Today (day 0)
- [ ] Review all cards (Mermaid mindmap + HTML + ASCII)

## Spaced intervals (adapt Ebbinghaus)
- Day 1, 3, 7, 14, 30...
- Re-extract / re-viz if retention <70% or new related reading.

Next: Feed this dir to archviz for more diagrams (e.g. process flows from concepts).
"""
    (out_dir / "review-log.md").write_text(log, encoding="utf-8")

    print(f"✓ Workflow complete. Artifacts in: {out_dir}")
    print("  - concept-mindmap.mmd (use with archviz / termaid)")
    print("  - vocab-cards.html (open in browser for review)")
    print("  - concept-cards-ascii.txt (terminal / plain)")
    print("  - review-log.md (track spaced repetition)")
    print("\nIntegrate: cat the mmd | termaid --theme mono")
    print("Or prompt agent: 'Use archviz on the concepts in this dir to make additional flow diagrams.'")

if __name__ == "__main__":
    main()
